language: elixir
elixir:
  - 1.3.4
  - 1.4.2
otp_release:
  - 18.2
  - 19.2
matrix:
  exclude:
    - elixir: 1.4.2
      otp_release: 18.2
    - elixir: 1.3.4
      otp_release: 19.2
sudo: false
env:
  - MIX_ENV=test STRIPE_SECRET_KEY=non_empty_secret_key_string
script: mix coveralls.travis
after_script:
  - mix inch.report
